services:
  robopin-next:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - haishan-static-network

networks:
  haishan-static-network:
    driver: bridge
